In [2]:
import numpy as np

In [12]:
ALL_MOVES=['G00','G01', 'G02', 'G03','G04', 'G05', 'G06', 'G07', 'G08', 'G09', 'G10',
       'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19','G20',
       'G21', 'G22', 'G23','G24',
       'G0500', 'G0100', 'G0600', 'G0601', 'G0001', 'G0201', 'G0702',
       'G0102', 'G0302', 'G0802', 'G0602', 'G0803', 'G0203', 'G0403',
       'G0904', 'G0304', 'G0804', 'G0005', 'G1005', 'G0605', 'G0106',
       'G1106', 'G0506', 'G0706', 'G0006', 'G1206', 'G0206', 'G1006',
       'G0207', 'G1207', 'G0607', 'G0807', 'G0308', 'G1308', 'G0708',
       'G0908', 'G0208', 'G1408', 'G0408', 'G1208', 'G0409', 'G1409',
       'G0809', 'G0510', 'G1510', 'G1110', 'G1610', 'G0610', 'G0611',
       'G1611', 'G1011', 'G1211', 'G0712', 'G1712', 'G1112', 'G1312',
       'G0612', 'G1812', 'G0812', 'G1612', 'G0813', 'G1813', 'G1213',
       'G1413', 'G0914', 'G1914', 'G1314', 'G0814', 'G1814', 'G1015',
       'G2015', 'G1615', 'G1116', 'G2116', 'G1516', 'G1716', 'G1016',
       'G2216', 'G1216', 'G2016', 'G1217', 'G2217', 'G1617', 'G1817',
       'G1318', 'G2318', 'G1718', 'G1918', 'G1218', 'G2418', 'G1418',
       'G2218', 'G1419', 'G2419', 'G1819', 'G1520', 'G2120', 'G1620',
       'G1621', 'G2021', 'G2221', 'G1722', 'G2122', 'G2322', 'G1622',
       'G1822', 'G1823', 'G2223', 'G2423', 'G1924', 'G2324', 'G1824',
       'nomovegoat',
       'B0500', 'B0100', 'B0600', 'B0601', 'B0001', 'B0201', 'B0702',
       'B0102', 'B0302', 'B0802', 'B0602', 'B0803', 'B0203', 'B0403',
       'B0904', 'B0304', 'B0804', 'B0005', 'B1005', 'B0605', 'B0106',
       'B1106', 'B0506', 'B0706', 'B0006', 'B1206', 'B0206', 'B1006',
       'B0207', 'B1207', 'B0607', 'B0807', 'B0308', 'B1308', 'B0708',
       'B0908', 'B0208', 'B1408', 'B0408', 'B1208', 'B0409', 'B1409',
       'B0809', 'B0510', 'B1510', 'B1110', 'B1610', 'B0610', 'B0611',
       'B1611', 'B1011', 'B1211', 'B0712', 'B1712', 'B1112', 'B1312',
       'B0612', 'B1812', 'B0812', 'B1612', 'B0813', 'B1813', 'B1213',
       'B1413', 'B0914', 'B1914', 'B1314', 'B0814', 'B1814', 'B1015',
       'B2015', 'B1615', 'B1116', 'B2116', 'B1516', 'B1716', 'B1016',
       'B2216', 'B1216', 'B2016', 'B1217', 'B2217', 'B1617', 'B1817',
       'B1318', 'B2318', 'B1718', 'B1918', 'B1218', 'B2418', 'B1418',
       'B2218', 'B1419', 'B2419', 'B1819', 'B1520', 'B2120', 'B1620',
       'B1621', 'B2021', 'B2221', 'B1722', 'B2122', 'B2322', 'B1622',
       'B1822', 'B1823', 'B2223', 'B2423', 'B1924', 'B2324', 'B1824',
       'B100005', 'B020001', 'B120006', 'B110106', 'B030102', 'B120207',
       'B000201', 'B040203', 'B140208', 'B100206', 'B130308', 'B010302',
       'B140409', 'B020403', 'B120408', 'B150510', 'B070506', 'B160611',
       'B080607', 'B180612', 'B170712', 'B050706', 'B090708', 'B180813',
       'B060807', 'B160812', 'B190914', 'B070908', 'B001005', 'B201015',
       'B121011', 'B221016', 'B021006', 'B011106', 'B211116', 'B131112',
       'B021207', 'B221217', 'B101211', 'B141213', 'B001206', 'B241218',
       'B041208', 'B201216', 'B031308', 'B231318', 'B111312', 'B041409',
       'B241419', 'B121413', 'B021408', 'B221418', 'B051510', 'B171516',
       'B061611', 'B181617', 'B081612', 'B071712', 'B151716', 'B191718',
       'B081813', 'B161817', 'B061812', 'B091914', 'B171918', 'B102015',
       'B222021', 'B122016', 'B112116', 'B232122', 'B122217', 'B202221',
       'B242223', 'B102216', 'B142218', 'B132318', 'B212322', 'B142419',
       'B222423', 'B122418',
       'nomovebagh']


In [14]:
a=np.arange(25)
a.shape=(5,5)

In [19]:
from scipy.ndimage import rotate

In [20]:
a,rotate(a, angle=90),rotate(a, angle=180),rotate(a, angle=270)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[ 4,  9, 14, 19, 24],
        [ 3,  8, 13, 18, 23],
        [ 2,  7, 12, 17, 22],
        [ 1,  6, 11, 16, 21],
        [ 0,  5, 10, 15, 20]]),
 array([[24, 23, 22, 21, 20],
        [19, 18, 17, 16, 15],
        [14, 13, 12, 11, 10],
        [ 9,  8,  7,  6,  5],
        [ 4,  3,  2,  1,  0]]),
 array([[20, 15, 10,  5,  0],
        [21, 16, 11,  6,  1],
        [22, 17, 12,  7,  2],
        [23, 18, 13,  8,  3],
        [24, 19, 14,  9,  4]]))

In [17]:
a_ud=np.flipud(a)
a_ud,rotate(a_ud, angle=90),rotate(a_ud, angle=180),rotate(a_ud, angle=270)

(array([[20, 21, 22, 23, 24],
        [15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]]),
 array([[24, 19, 14,  9,  4],
        [23, 18, 13,  8,  3],
        [22, 17, 12,  7,  2],
        [21, 16, 11,  6,  1],
        [20, 15, 10,  5,  0]]),
 array([[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15],
        [24, 23, 22, 21, 20]]),
 array([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]]))

In [31]:
a=a 
a_r90=rotate(a, angle=90)

a_r90

array([[ 4,  9, 14, 19, 24],
       [ 3,  8, 13, 18, 23],
       [ 2,  7, 12, 17, 22],
       [ 1,  6, 11, 16, 21],
       [ 0,  5, 10, 15, 20]])

In [36]:
a_r90=a_r90.flatten()
a_r90

array([ 4,  9, 14, 19, 24,  3,  8, 13, 18, 23,  2,  7, 12, 17, 22,  1,  6,
       11, 16, 21,  0,  5, 10, 15, 20])

In [38]:
a_r90[2]

14

In [64]:
'yut_uiu'.split('_')[-1]

'uiu'

In [65]:
a=np.arange(25)
a.shape=(5,5)
a_ud=np.flipud(a)

symmetry_moves_dct={}
s_codes=['90','180','270','u_0','u_90','u_180','u_270']

for s_code in s_codes:
    #[rotate(a, angle=90),rotate(a, angle=180),rotate(a, angle=270),a_ud,rotate(a_ud, angle=90),rotate(a_ud, angle=180),rotate(a_ud, angle=270)]:
    a=np.arange(25)
    a.shape=(5,5)
    if 'u' in s_code:
        a=np.flipud(a)
    a=rotate(a,angle=int(s_code.split('_')[-1]))
    flat_symmetry=a.flatten()
    dct={}

    for move in ALL_MOVES:
        s=str(move)
        i,j=1,3
        if move[:2]!='no': # filter nomoves
            pick=int(move[i:j])
            s=s[:i] + f"{flat_symmetry[pick]:02}" + s[j:] #f"{a:02}"

            i,j=3,5
            if move[i:j]: 
                pick=int(move[i:j])
                s=s[:i] + f"{flat_symmetry[pick]:02}" + s[j:]

                i,j=5,7
                if move[i:j]: 
                    pick=int(move[i:j])
                    s=s[:i] + f"{flat_symmetry[pick]:02}" + s[j:]
        dct[move]=s
    symmetry_moves_dct[s_code]=dct

symmetry_moves_dct

{'90': {'G00': 'G04',
  'G01': 'G09',
  'G02': 'G14',
  'G03': 'G19',
  'G04': 'G24',
  'G05': 'G03',
  'G06': 'G08',
  'G07': 'G13',
  'G08': 'G18',
  'G09': 'G23',
  'G10': 'G02',
  'G11': 'G07',
  'G12': 'G12',
  'G13': 'G17',
  'G14': 'G22',
  'G15': 'G01',
  'G16': 'G06',
  'G17': 'G11',
  'G18': 'G16',
  'G19': 'G21',
  'G20': 'G00',
  'G21': 'G05',
  'G22': 'G10',
  'G23': 'G15',
  'G24': 'G20',
  'G0500': 'G0304',
  'G0100': 'G0904',
  'G0600': 'G0804',
  'G0601': 'G0809',
  'G0001': 'G0409',
  'G0201': 'G1409',
  'G0702': 'G1314',
  'G0102': 'G0914',
  'G0302': 'G1914',
  'G0802': 'G1814',
  'G0602': 'G0814',
  'G0803': 'G1819',
  'G0203': 'G1419',
  'G0403': 'G2419',
  'G0904': 'G2324',
  'G0304': 'G1924',
  'G0804': 'G1824',
  'G0005': 'G0403',
  'G1005': 'G0203',
  'G0605': 'G0803',
  'G0106': 'G0908',
  'G1106': 'G0708',
  'G0506': 'G0308',
  'G0706': 'G1308',
  'G0006': 'G0408',
  'G1206': 'G1208',
  'G0206': 'G1408',
  'G1006': 'G0208',
  'G0207': 'G1413',
  'G1207': 'G1