In [1]:
import  sys, os
sys.path.insert(0, os.path.dirname(os.getcwd()))

In [3]:
os.path.dirname(os.getcwd())+'\\game'

'e:\\deepbaghchal\\deepbaghchal\\game'

In [2]:
[9,8]+[2,3,4]

[9, 8, 2, 3, 4]

In [3]:
import numpy as np

In [16]:
l=[2,3,4,5]
n=np.array(l)

In [8]:
n

array([2, 3, 4, 5])

In [17]:
n2=np.reshape(l, (2, 2))
n2

array([[2, 3],
       [4, 5]])

In [14]:
np.fliplr(n2)

array([[3, 2],
       [5, 4]])

In [15]:
np.flipud(n2)

array([[4, 5],
       [2, 3]])

In [18]:
ALL_MOVES=['G00','G01', 'G02', 'G03','G04', 'G05', 'G06', 'G07', 'G08', 'G09', 'G10',
       'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19','G20',
       'G21', 'G22', 'G23','G24',
       'G0500', 'G0100', 'G0600', 'G0601', 'G0001', 'G0201', 'G0702',
       'G0102', 'G0302', 'G0802', 'G0602', 'G0803', 'G0203', 'G0403',
       'G0904', 'G0304', 'G0804', 'G0005', 'G1005', 'G0605', 'G0106',
       'G1106', 'G0506', 'G0706', 'G0006', 'G1206', 'G0206', 'G1006',
       'G0207', 'G1207', 'G0607', 'G0807', 'G0308', 'G1308', 'G0708',
       'G0908', 'G0208', 'G1408', 'G0408', 'G1208', 'G0409', 'G1409',
       'G0809', 'G0510', 'G1510', 'G1110', 'G1610', 'G0610', 'G0611',
       'G1611', 'G1011', 'G1211', 'G0712', 'G1712', 'G1112', 'G1312',
       'G0612', 'G1812', 'G0812', 'G1612', 'G0813', 'G1813', 'G1213',
       'G1413', 'G0914', 'G1914', 'G1314', 'G0814', 'G1814', 'G1015',
       'G2015', 'G1615', 'G1116', 'G2116', 'G1516', 'G1716', 'G1016',
       'G2216', 'G1216', 'G2016', 'G1217', 'G2217', 'G1617', 'G1817',
       'G1318', 'G2318', 'G1718', 'G1918', 'G1218', 'G2418', 'G1418',
       'G2218', 'G1419', 'G2419', 'G1819', 'G1520', 'G2120', 'G1620',
       'G1621', 'G2021', 'G2221', 'G1722', 'G2122', 'G2322', 'G1622',
       'G1822', 'G1823', 'G2223', 'G2423', 'G1924', 'G2324', 'G1824',
       'nomovegoat',
       'B0500', 'B0100', 'B0600', 'B0601', 'B0001', 'B0201', 'B0702',
       'B0102', 'B0302', 'B0802', 'B0602', 'B0803', 'B0203', 'B0403',
       'B0904', 'B0304', 'B0804', 'B0005', 'B1005', 'B0605', 'B0106',
       'B1106', 'B0506', 'B0706', 'B0006', 'B1206', 'B0206', 'B1006',
       'B0207', 'B1207', 'B0607', 'B0807', 'B0308', 'B1308', 'B0708',
       'B0908', 'B0208', 'B1408', 'B0408', 'B1208', 'B0409', 'B1409',
       'B0809', 'B0510', 'B1510', 'B1110', 'B1610', 'B0610', 'B0611',
       'B1611', 'B1011', 'B1211', 'B0712', 'B1712', 'B1112', 'B1312',
       'B0612', 'B1812', 'B0812', 'B1612', 'B0813', 'B1813', 'B1213',
       'B1413', 'B0914', 'B1914', 'B1314', 'B0814', 'B1814', 'B1015',
       'B2015', 'B1615', 'B1116', 'B2116', 'B1516', 'B1716', 'B1016',
       'B2216', 'B1216', 'B2016', 'B1217', 'B2217', 'B1617', 'B1817',
       'B1318', 'B2318', 'B1718', 'B1918', 'B1218', 'B2418', 'B1418',
       'B2218', 'B1419', 'B2419', 'B1819', 'B1520', 'B2120', 'B1620',
       'B1621', 'B2021', 'B2221', 'B1722', 'B2122', 'B2322', 'B1622',
       'B1822', 'B1823', 'B2223', 'B2423', 'B1924', 'B2324', 'B1824',
       'B100005', 'B020001', 'B120006', 'B110106', 'B030102', 'B120207',
       'B000201', 'B040203', 'B140208', 'B100206', 'B130308', 'B010302',
       'B140409', 'B020403', 'B120408', 'B150510', 'B070506', 'B160611',
       'B080607', 'B180612', 'B170712', 'B050706', 'B090708', 'B180813',
       'B060807', 'B160812', 'B190914', 'B070908', 'B001005', 'B201015',
       'B121011', 'B221016', 'B021006', 'B011106', 'B211116', 'B131112',
       'B021207', 'B221217', 'B101211', 'B141213', 'B001206', 'B241218',
       'B041208', 'B201216', 'B031308', 'B231318', 'B111312', 'B041409',
       'B241419', 'B121413', 'B021408', 'B221418', 'B051510', 'B171516',
       'B061611', 'B181617', 'B081612', 'B071712', 'B151716', 'B191718',
       'B081813', 'B161817', 'B061812', 'B091914', 'B171918', 'B102015',
       'B222021', 'B122016', 'B112116', 'B232122', 'B122217', 'B202221',
       'B242223', 'B102216', 'B142218', 'B132318', 'B212322', 'B142419',
       'B222423', 'B122418',
       'nomovebagh']



In [19]:
len(ALL_MOVES)

331

In [20]:
aa=np.array(ALL_MOVES)

In [24]:
np.in1d(ALL_MOVES, ['B1213','G02', 'G03','G04', 'G05', 'G06', 'G07','nomovebagh'])

array([False, False,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,