In [1]:
lst=['B000B000000000000000Bg00B0B', 'B00000000B0000000000Bg00B0g', 'B00000000B00g0000000Bg00B0B', '000000B00B00g0000000Bg00B0g', '000000B00B00g000g000Bg00B0B']

In [2]:
import numpy as np

In [3]:
ar=np.array(lst)

In [4]:
ar[:3]

array(['B000B000000000000000Bg00B0B', 'B00000000B0000000000Bg00B0g',
       'B00000000B00g0000000Bg00B0B'], dtype='<U27')

In [6]:
!pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 3.6 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 18.0 MB/s eta 0:00:00
     ------------------------------------- 895.9/895.9 kB 18.8 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 18.4 MB/s eta 0:00:00
     ---------------------------------------- 2.6/2.6 MB 18.8 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 18.9 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 7.3 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     --------------------------------------- 23.2/23.2 MB 13.9 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ------------------------------------- 439.2/439.2 kB 26.8 MB/s eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 18.2 MB/s eta 0:00:00
     ----------------------------------------


[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import tensorflow as tf

# Set up the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(100,)),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model with an appropriate optimizer, loss function, and metric(s)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print a summary of the model architecture
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 300)               30300     
                                                                 
 dense_1 (Dense)             (None, 300)               90300     
                                                                 
 dense_2 (Dense)             (None, 300)               90300     
                                                                 
 dense_3 (Dense)             (None, 300)               90300     
                                                                 
 dense_4 (Dense)             (None, 300)               90300     
                                                                 
 dense_5 (Dense)             (None, 1)                 301       
                                                                 
Total params: 391,801
Trainable params: 391,801
Non-trai

In [2]:
import numpy as np

# Generate some random input data
num_samples = 1000
input_size = 100
input_data = np.random.rand(num_samples, input_size)

# Verify the shape of the input data
print(input_data.shape)


(1000, 100)


In [3]:
input_data

array([[0.38552856, 0.9810225 , 0.82564707, ..., 0.82216333, 0.40452161,
        0.1634153 ],
       [0.75301194, 0.3578934 , 0.80538419, ..., 0.36030219, 0.79864063,
        0.0982985 ],
       [0.98562338, 0.57796813, 0.20852601, ..., 0.39356429, 0.83939757,
        0.57782587],
       ...,
       [0.6603617 , 0.41677158, 0.61285225, ..., 0.84734286, 0.62802872,
        0.23897114],
       [0.4752433 , 0.6079343 , 0.2884341 , ..., 0.81220924, 0.47379959,
        0.87319007],
       [0.73435211, 0.46401907, 0.67267255, ..., 0.89763409, 0.96137752,
        0.44900677]])

In [13]:
import numpy as np

pos = 'B000B000000000000000Bg00B0B'
my_list = list(pos[:25])

bagh = np.array([1 if x == 'B' else 0 for x in my_list])
goat = np.array([1 if x == 'g' else 0 for x in my_list])
turn=np.zeros(25)
phase=np.ones(25)


print(np.concatenate([bagh,goat,turn,phase]))

[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [14]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

two_dim_array = np.vstack((array1, array2))

print(two_dim_array)


[[1 2 3]
 [4 5 6]]


In [12]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate([array1, array2])

print(concatenated_array)


[1 2 3 4 5 6]


In [17]:
import numpy as np

# create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# shuffle the array along the first axis
np.random.shuffle(my_array)

print(my_array)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [18]:
import numpy as np

# create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# create a new column to append to the array
new_column = np.array([10, 11, 12])

# append the new column to the array using append with axis=1
my_array = np.append(my_array, np.expand_dims(new_column, axis=1), axis=1)

print(my_array)


[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [2]:
def reader(filename):
    with open('../simul/data/'+filename+'.txt', 'r') as file:
        lines = file.readlines()
        lines = [line.strip() for line in lines]
        return lines

In [7]:
def pos_parse(pos):
    print(pos)
    my_list = list(pos[:25])

    bagh = np.array([1 if x == 'B' else 0 for x in my_list])
    goat = np.array([1 if x == 'g' else 0 for x in my_list])
    if pos[25]=='0':
        phase=np.zeros(25)
    else:
        phase=np.ones(25)

    if pos[26]=='B':
        turn=np.zeros(25)
    else:
        turn=np.ones(25)

    return np.concatenate([bagh,goat,turn,phase])

In [15]:
bagh=reader('baghWinList')

bagh_arr=pos_parse(bagh[0])
for pos in bagh[1:4]:
    pos_arr=pos_parse(pos)
    bagh_arr=np.vstack((bagh_arr, pos_arr))   
print(bagh_arr) 


B000B000000000000000Bg00B0B
B00000000B0000000000Bg00B0g
B00000000B00g0000000Bg00B0B
000000B00B00g0000000Bg00B0g
[[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [17]:
# append the new column to the array using append with axis=1
my_array = np.append(bagh_arr, np.expand_dims(np.ones(len(bagh_arr)), axis=1), axis=1)

print(my_array)

[[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [26]:
np.random.shuffle(my_array)

In [27]:
import numpy as np

# create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# get the last column as a 1D array using indexing and slicing
last_column = my_array[:, -1]

print(last_column)

[3 6 9]


In [1]:
import numpy as np

# Create a sample 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Shuffle the rows of the array
np.random.shuffle(my_array)

print(my_array)


[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [7]:
len('g00Bggg0Bg00Bggg0gggBgggg1g')

27

In [17]:
import numpy as np
# read data

def reader(filename):
    with open('../simul/data/'+filename+'.txt', 'r') as file:
        lines = file.readlines()
        lines = [line.strip() for line in lines]
        return lines

        
def pos_parse(pos):
    my_list = list(pos[:25])

    bagh = np.array([1 if x == 'B' else 0 for x in my_list])
    goat = np.array([1 if x == 'g' else 0 for x in my_list])
    if pos[25]=='0':
        phase=np.zeros(25)
    else:
        phase=np.ones(25)

    if pos[26]=='B':
        turn=np.zeros(25)
    else:
        turn=np.ones(25)

    return np.concatenate([bagh,goat,turn,phase])


def combine_pos(lst):
    my_arr=pos_parse(lst[0])
    for pos in lst:
        pos_arr=pos_parse(pos)
        my_arr=np.vstack((my_arr, pos_arr))
    
    return my_arr

def prepare_data():
    bagh=reader('baghWinList')
    bagh_arr=combine_pos(bagh[:1000])
    bagh_arr = np.append(bagh_arr, np.expand_dims(np.zeros(len(bagh_arr)), axis=1), axis=1)

    goat=reader('goatWinList')
    goat_arr=combine_pos(goat[:1000])
    goat_arr = np.append(goat_arr, np.expand_dims(np.ones(len(goat_arr)), axis=1), axis=1)


    #draw=reader('drawList')

    #concat and shuffle
    both=np.concatenate((bagh_arr,goat_arr), axis=0)
    np.random.shuffle(both)
    print(both[:4])
    return both

print('preparing Data')
data=prepare_data()
print(data)
input_arr=data[:,:-1]
output_arr=data[:,-1]

# neural net

import tensorflow as tf

# Set up the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(100,)),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model with an appropriate optimizer, loss function, and metric(s)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



#train function



print('Fitting model')
history = model.fit(input_arr, output_arr, epochs=10, batch_size=32, verbose=1)
# Save the trained model to a file
model.save('my_model.h5')


preparing Data
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1.
  0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1.
  1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0.
  0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.

In [9]:
l=np.array([[0.93916214]])
l[0][0]

0.93916214

In [12]:
randoms_turn=True

randoms_turn^=1
randoms_turn

0

In [13]:
randoms_turn^=1
randoms_turn

1